#!/usr/bin/env python3
# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate TileOPs -> aten routing tables from the TileOPs manifest.

Reads ``tileops/manifest/*.yaml`` plus the hand-maintained tables in
``torch_fl/tileops_spec.py`` and writes:

  - ``torch_fl/generated/tileops_routes.py``      routing table
  - ``torch_fl/configs/backends_tileops.conf``    per-op backend selection
  - ``tests/integration/ops/test_tileops_generated.py``  numeric + dispatch tests

Products are committed, matching how ``csrc/aten/generated/`` is handled: routing
changes show up in review and the build never needs TileOPs installed.

Usage (needs tileops importable, e.g. PYTHONPATH=/path/to/tilelang-env):

    python scripts/codegen_tileops.py [--check]

``--check`` regenerates into memory and fails if the committed files differ,
which is what CI should run.

Output is piped through ``ruff format`` so the products satisfy the repo lint
job. Without that, ``ruff format .`` rewrites them and ``--check`` immediately
reports them stale -- the two gates would contradict each other.
"""

from __future__ import annotations

import argparse
import collections
import importlib
import inspect
import pathlib
import re
import shutil
import subprocess
import sys
from typing import Dict, List, Optional, Tuple

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from torch_fl.tileops_spec import (  # noqa: E402
    ATEN_ALIAS,
    ATEN_OVERLOAD,
    BINARY,
    DEFAULT_OFF,
    EXCLUDE,
    RECIPES,
    REDUCE,
    SOFTMAX,
    UNARY,
)

CONF_CUDA = REPO / "torch_fl" / "configs" / "backends_cuda.conf"
OUT_ROUTES = REPO / "torch_fl" / "generated" / "tileops_routes.py"
OUT_CONF = REPO / "torch_fl" / "configs" / "backends_tileops.conf"
OUT_TEST = REPO / "tests" / "integration" / "ops" / "test_tileops_generated.py"

LICENSE = """# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""

BANNER = "# AUTO-GENERATED by scripts/codegen_tileops.py -- DO NOT EDIT."

# ctor params that are plumbing rather than op semantics
CTOR_IGNORE = {"self", "kernel_map", "tune"}

# dtype token (manifest spelling) -> torch dtype attribute name
DTYPE_TOKENS = {
    "float16": "float16",
    "bfloat16": "bfloat16",
    "float32": "float32",
    "float64": "float64",
    "int8": "int8",
    "int16": "int16",
    "int32": "int32",
    "int64": "int64",
    "uint8": "uint8",
    "bool": "bool",
}


# --------------------------------------------------------------------------- #
# manifest / class discovery
# --------------------------------------------------------------------------- #
def load_manifest() -> Dict[str, dict]:
    try:
        import yaml
    except ImportError:
        sys.exit("codegen_tileops: PyYAML required")
    try:
        import tileops.manifest as man_pkg
    except ImportError as exc:
        sys.exit(f"codegen_tileops: cannot import tileops ({exc}); set PYTHONPATH")

    man_dir = pathlib.Path(man_pkg.__file__).parent
    entries: Dict[str, dict] = {}
    for path in sorted(man_dir.glob("*.yaml")):
        data = yaml.safe_load(path.read_text()) or {}
        for name, spec in data.items():
            if isinstance(spec, dict) and "ref_api" in spec:
                spec = dict(spec)
                spec["_family"] = path.stem
                entries[name] = spec
    return entries


def load_op_classes() -> Dict[str, type]:
    """Map Op class name -> class, walking every module under tileops.ops."""
    import tileops.ops as ops_pkg

    ops_dir = pathlib.Path(ops_pkg.__file__).parent
    root = ops_dir.parent.parent
    classes: Dict[str, type] = {}
    for path in sorted(ops_dir.rglob("*.py")):
        mod = str(path.relative_to(root).with_suffix("")).replace("/", ".")
        try:
            module = importlib.import_module(mod)
        except Exception:
            continue
        for name, obj in vars(module).items():
            if inspect.isclass(obj) and name not in classes:
                classes[name] = obj
    return classes


def routed_aten_names() -> set:
    """Base aten names torch_fl already routes, taken from the CUDA conf."""
    names = set()
    for line in CONF_CUDA.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        names.add(line.split("=")[0].strip().split(".")[0])
    return names


def conf_entries() -> List[str]:
    """Every ``op = backend`` key in the CUDA conf, in file order."""
    out = []
    for line in CONF_CUDA.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        out.append(line.split("=")[0].strip())
    return out


# --------------------------------------------------------------------------- #
# classification
# --------------------------------------------------------------------------- #
def aten_base(ref_api: str) -> Optional[str]:
    if not ref_api:
        return None
    if ref_api in ATEN_ALIAS:
        return ATEN_ALIAS[ref_api]
    return ref_api.split("(")[0].strip().split(".")[-1]


def ctor_params(cls: type) -> Optional[Tuple[str, ...]]:
    try:
        sig = inspect.signature(cls.__init__)
    except (TypeError, ValueError):
        return None
    return tuple(p for p in sig.parameters if p not in CTOR_IGNORE)


def forward_params(cls: type) -> Optional[Tuple[str, ...]]:
    try:
        sig = inspect.signature(cls.forward)
    except (TypeError, ValueError):
        return None
    return tuple(p for p in sig.parameters if p != "self")


def dtypes_for(op_name: str, cls: type, spec: dict) -> Tuple[str, ...]:
    """Supported dtypes as torch attribute names.

    Prefers ``cls.kernel_cls.SUPPORTED_DTYPES`` (readable without instantiating,
    covers ~half the ops) and falls back to the manifest dtype strings, which
    cover all of them.
    """
    kernel_cls = getattr(cls, "kernel_cls", None)
    supported = getattr(kernel_cls, "SUPPORTED_DTYPES", None) if kernel_cls else None
    if supported:
        out = []
        for dt in supported:
            name = str(dt).replace("torch.", "")
            if name in DTYPE_TOKENS:
                out.append(name)
        if out:
            return tuple(out)

    tokens: List[str] = []
    for field in (spec.get("signature", {}).get("inputs", {}) or {}).values():
        if not isinstance(field, dict):
            continue
        raw = field.get("dtype")
        if not raw or "same_as" in str(raw):
            continue
        for tok in re.split(r"[|,]", str(raw)):
            tok = tok.strip()
            if tok in DTYPE_TOKENS and tok not in tokens:
                tokens.append(tok)
        if tokens:
            break
    return tuple(tokens)


Route = collections.namedtuple(
    "Route", "aten overload recipe module cls_name op_name dtypes extra workload family"
)


def first_workload(spec: dict) -> Optional[list]:
    for wl in spec.get("workloads") or []:
        for key, val in wl.items():
            if key.endswith("_shape") and isinstance(val, list):
                return val
    return None


def classify(entries: Dict[str, dict], classes: Dict[str, type]):
    routed = routed_aten_names()
    routes: List[Route] = []
    manual: Dict[Tuple[str, ...], List[str]] = collections.defaultdict(list)
    skipped: Dict[str, str] = {}

    for op_name, spec in sorted(entries.items()):
        if spec.get("status") != "implemented":
            continue
        base = aten_base(spec.get("ref_api"))
        if not base or base not in routed:
            continue
        if op_name in EXCLUDE:
            skipped[op_name] = EXCLUDE[op_name]
            continue

        cls = classes.get(op_name)
        if cls is None:
            skipped[op_name] = "Op class not importable"
            continue

        ctor = ctor_params(cls)
        recipe = RECIPES.get(ctor)
        if recipe is None:
            manual[ctor or ()].append(op_name)
            continue

        dtypes = dtypes_for(op_name, cls, spec)
        if not dtypes:
            skipped[op_name] = "no dtype set from kernel_cls or manifest"
            continue

        extra = {}
        if "inplace" in (ctor or ()):
            extra["inplace"] = False
        if "keepdim" in (ctor or ()):
            extra["keepdim"] = True
        if "alpha" in (ctor or ()):
            extra["alpha"] = True
        if "correction" in (ctor or ()):
            extra["correction"] = True
        if "ord" in (ctor or ()):
            extra["ord"] = True

        routes.append(
            Route(
                aten=base,
                overload=ATEN_OVERLOAD.get(base, base),
                recipe=recipe,
                module=cls.__module__,
                cls_name=op_name,
                op_name=op_name,
                dtypes=dtypes,
                extra=extra,
                workload=first_workload(spec),
                family=spec.get("_family", "?"),
            )
        )

    validate(routes, classes)
    return routes, manual, skipped


def validate(routes: List[Route], classes: Dict[str, type]) -> None:
    """Fail loudly rather than emit code that cannot work.

    Each recipe implies an arity on ``forward``; if TileOPs changes a signature we
    want a codegen failure, not a runtime one.
    """
    expected = {UNARY: 1, BINARY: 2, REDUCE: 1, SOFTMAX: 1}
    problems = []
    seen = {}
    for r in routes:
        fwd = forward_params(classes[r.cls_name]) or ()
        want = expected[r.recipe]
        if len(fwd) != want:
            problems.append(
                f"{r.cls_name}: recipe {r.recipe} expects {want} forward arg(s), got {list(fwd)}"
            )
        if r.overload in seen:
            problems.append(
                f"aten overload '{r.overload}' claimed by both {seen[r.overload]} and {r.cls_name}"
            )
        else:
            seen[r.overload] = r.cls_name
    if problems:
        sys.exit("codegen_tileops: validation failed\n  " + "\n  ".join(problems))


# --------------------------------------------------------------------------- #
# emission
# --------------------------------------------------------------------------- #
def render_routes(routes: List[Route], skipped: Dict[str, str]) -> str:
    lines = [
        LICENSE,
        "",
        BANNER,
        '"""TileOPs -> aten routing table generated from the TileOPs manifest.',
        "",
    ]
    lines += [
        "Modules are named as strings so importing this file never pulls in TileOPs;",
        "torch_fl.tileops_backend imports them lazily once the SM90/dependency gate",
        "passes.",
        '"""',
        "",
        "from torch_fl.tileops_spec import BINARY, REDUCE, SOFTMAX, UNARY",
        "",
    ]

    dtype_sets = collections.Counter(r.dtypes for r in routes)
    aliases = {}
    for i, (dts, _) in enumerate(dtype_sets.most_common()):
        aliases[dts] = f"_DT{i}"
        lines.append(f"{aliases[dts]} = {tuple(dts)!r}")
    lines.append("")
    lines.append("#: (aten_overload, recipe, module, op_class, dtype_names, extra)")
    lines.append("ROUTES = [")
    for r in sorted(routes, key=lambda x: (x.recipe, x.overload)):
        lines.append(
            f"    ({r.overload!r}, {r.recipe}, {r.module!r}, {r.cls_name!r}, "
            f"{aliases[r.dtypes]}, {r.extra!r}),"
        )
    lines.append("]")
    lines.append("")
    lines.append(
        "#: aten overload -> a manifest workload shape, for warmup and benchmarks."
    )
    lines.append("WORKLOADS = {")
    for r in sorted(routes, key=lambda x: x.overload):
        if r.workload:
            lines.append(f"    {r.overload!r}: {tuple(r.workload)!r},")
    lines.append("}")
    lines.append("")
    lines.append(
        "#: ops deliberately not routed, with the reason (see tileops_spec.EXCLUDE)."
    )
    lines.append("NOT_ROUTED = {")
    for name, why in sorted(skipped.items()):
        lines.append(f"    {name!r}: {why!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_conf(routes: List[Route]) -> str:
    on = {}
    for r in routes:
        if r.cls_name in DEFAULT_OFF:
            continue
        on[r.overload] = r.cls_name

    head = [
        LICENSE.rstrip(),
        "",
        "# flagos op backend config -- AUTO-GENERATED by scripts/codegen_tileops.py",
        "#",
        "# Same shape as backends_cuda.conf; only aten-aligned TileOPs ops are",
        "# switched to 'tileops'. Selected by FLAGOS_USE_TILEOPS=1.",
        "#",
        "# TileOPs kernels are bound through torch.library on PrivateUse1, which",
        "# runs ahead of the C++ dispatcher -- these entries exist so routing is",
        "# observable via FLAGOS_LOG_DISPATCH=1 and revertible per op via",
        "# FLAGOS_OP_<name>=cuda.",
        "#",
        f"# tileops-routed entries: {len(on)}",
        "",
    ]
    body = []
    for op in conf_entries():
        body.append(f"{op} = {'tileops' if op in on else 'cuda'}")
    return "\n".join(head + body) + "\n"


def render_test(routes: List[Route]) -> str:
    lines = [
        LICENSE,
        "",
        BANNER,
        '"""Numeric and dispatch coverage for generated TileOPs routes."""',
        "",
        "import os",
        "",
        "import pytest",
        "import torch",
        "",
        "import torch_fl  # noqa: F401",
        "from torch_fl import tileops_backend",
        "from torch_fl.generated.tileops_routes import ROUTES, WORKLOADS",
        "",
        "pytestmark = pytest.mark.skipif(",
        "    not tileops_backend.is_tileops_available(),",
        '    reason="TileOPs unavailable or host is not SM90",',
        ")",
        "",
        "",
        "def _ref(overload):",
        '    """Resolve an aten overload to a callable.',
        "",
        "    Called with CPU tensors on purpose: the flagos key is where the TileOPs",
        "    impl is bound, so a reference computed there would just re-enter the",
        "    implementation under test.",
        '    """',
        '    base, _, ov = overload.partition(".")',
        "    packet = getattr(torch.ops.aten, base)",
        "    return getattr(packet, ov) if ov else packet",
        "",
        "",
        "TOL = {",
        "    torch.float16: (1e-2, 1e-2),",
        "    torch.bfloat16: (5e-2, 5e-2),",
        "    torch.float32: (1e-4, 1e-5),",
        "}",
        "",
        "",
        "@pytest.mark.parametrize(",
        '    "overload,recipe,module,cls_name,dtypes,extra",',
        "    ROUTES,",
        "    ids=[r[0] for r in ROUTES],",
        ")",
        "def test_matches_aten(overload, recipe, module, cls_name, dtypes, extra):",
        '    """Generated route agrees with the aten reference.',
        "",
        "    Runs on a small shape by default. Every distinct shape costs a full",
        "    TileLang compile (~4 s, since the availability gate forces",
        "    TILELANG_DISABLE_CACHE=1 to dodge the upstream cache-key collision), so",
        "    the larger manifest workload shape is opt-in via FLAGOS_TILEOPS_FULL=1.",
        '    """',
        "    shape = (64, 32)",
        "    if os.environ.get('FLAGOS_TILEOPS_FULL') == '1':",
        "        shape = WORKLOADS.get(overload, shape)",
        "    dtype = getattr(torch, dtypes[0])",
        "",
        "    fn = tileops_backend.build_impl(recipe, module, cls_name, dtypes, extra, overload)",
        "    if fn is None:",
        '        pytest.skip("route not constructible on this host")',
        "",
        "    cpu_args = tileops_backend.sample_inputs(",
        "        recipe, shape, dtype, device='cpu', overload=overload",
        "    )",
        "    dev_args = tuple(",
        "        a.to('flagos') if isinstance(a, torch.Tensor) else a for a in cpu_args",
        "    )",
        "",
        "    got = fn(*dev_args)",
        "    want = _ref(overload)(*cpu_args)",
        "    if isinstance(got, (tuple, list)):",
        "        got = got[0]",
        "    if isinstance(want, (tuple, list)):",
        "        want = want[0]",
        "    if dtype in TOL:",
        "        rtol, atol = TOL[dtype]",
        "        torch.testing.assert_close(",
        "            got.cpu().float(), want.float(), rtol=rtol, atol=atol",
        "        )",
        "    else:",
        "        # Integer and bool results must be bit-exact.",
        "        assert torch.equal(got.cpu(), want)",
        "",
        "",
        "def test_dtype_guard_falls_back():",
        '    """An unsupported dtype must fall back to aten, not raise."""',
        "    x = torch.ones(64, device='flagos', dtype=torch.int32)",
        "    assert torch.equal(torch.relu(x), x)",
        "",
        "",
        "def test_enable_is_idempotent():",
        '    """Re-enabling must not double-register or grow the instance cache."""',
        "    first = tileops_backend.enable_tileops_for_flagos()",
        "    second = tileops_backend.enable_tileops_for_flagos()",
        "    assert first == second",
        "",
        "",
        "@pytest.mark.parametrize('overload', [r[0] for r in ROUTES])",
        "def test_registered_on_privateuse1(overload):",
        '    """Every generated route is actually bound for the flagos key."""',
        "    tileops_backend.enable_tileops_for_flagos()",
        "    assert overload in tileops_backend.registered_ops()",
        "",
        "",
        "def test_env_override_is_consulted(monkeypatch):",
        '    """FLAGOS_OP_<op>=cuda must keep the op off the tileops path.',
        "",
        "    A PrivateUse1 binding intercepts before the C++ dispatcher, so honoring",
        "    the override there alone is not enough -- the op has to stay unbound.",
        "    Only the decision is asserted here: a PrivateUse1 binding made by an",
        "    earlier test cannot be undone, so re-running enable() proves nothing.",
        '    """',
        "    monkeypatch.setenv('FLAGOS_OP_relu', 'cuda')",
        "    monkeypatch.setenv('FLAGOS_OP_sum__dim_IntList', 'cuda')",
        "    assert tileops_backend._env_override_backend('relu') == 'cuda'",
        "    assert tileops_backend._env_override_backend('sum.dim_IntList') == 'cuda'",
        "    assert tileops_backend._env_override_backend('sigmoid') is None",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
def ruff_format(text: str, filename: str) -> str:
    """Run ``ruff format`` over generated source, matching the lint job.

    Returns the input unchanged when ruff is absent, so codegen still works on a
    box without it -- but ``--check`` then compares against unformatted text and
    can disagree with CI, hence the warning.
    """
    ruff = shutil.which("ruff")
    if ruff is None:
        print(
            f"codegen_tileops: ruff not found, {filename} left unformatted "
            "(install ruff to match the lint job)",
            file=sys.stderr,
        )
        return text
    done = subprocess.run(
        [ruff, "format", "--stdin-filename", filename, "-"],
        input=text,
        capture_output=True,
        text=True,
    )
    if done.returncode != 0:
        raise RuntimeError(f"ruff format failed on {filename}: {done.stderr.strip()}")
    return done.stdout


# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true", help="fail if committed output is stale"
    )
    args = ap.parse_args()

    entries = load_manifest()
    classes = load_op_classes()
    routes, manual, skipped = classify(entries, classes)

    products = {
        OUT_ROUTES: ruff_format(render_routes(routes, skipped), OUT_ROUTES.name),
        OUT_CONF: render_conf(routes),  # not python, ruff would reject it
        OUT_TEST: ruff_format(render_test(routes), OUT_TEST.name),
    }

    if args.check:
        stale = [
            p.name
            for p, text in products.items()
            if not p.exists() or p.read_text() != text
        ]
        if stale:
            print(
                "codegen_tileops: stale products: " + ", ".join(stale), file=sys.stderr
            )
            print("re-run: python scripts/codegen_tileops.py", file=sys.stderr)
            return 1
        print("codegen_tileops: products up to date")
        return 0

    for path, text in products.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(REPO)}")

    by_recipe = collections.Counter(r.recipe for r in routes)
    print(f"\nrouted {len(routes)} ops: {dict(by_recipe)}")
    print(f"default-off (conf says cuda): {sorted(DEFAULT_OFF)}")
    print(f"excluded {len(skipped)}: {sorted(skipped)}")
    n_manual = sum(len(v) for v in manual.values())
    print(
        f"\nmanual recipes still needed: {n_manual} ops across {len(manual)} ctor shapes"
    )
    for ctor, ops in sorted(manual.items(), key=lambda kv: -len(kv[1])):
        print(f"  {list(ctor)} -> {sorted(ops)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
