# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# AUTO-GENERATED by scripts/codegen_tileops.py -- DO NOT EDIT.
"""Numeric and dispatch coverage for generated TileOPs routes."""

import os
import subprocess
import sys

import pytest
import torch

import torch_fl  # noqa: F401
from torch_fl import tileops_backend
from torch_fl.generated.tileops_routes import ROUTES, WORKLOADS
from torch_fl.generated.tileops_shims import SHIM_NAMES

pytestmark = pytest.mark.skipif(
    not tileops_backend.is_tileops_available(),
    reason="TileOPs unavailable or host is not SM90",
)


def _ref(overload):
    """Resolve an aten overload to a callable.

    Called with CPU tensors on purpose: the flagos key is where the TileOPs
    impl is bound, so a reference computed there would just re-enter the
    implementation under test.
    """
    base, _, ov = overload.partition(".")
    packet = getattr(torch.ops.aten, base)
    return getattr(packet, ov) if ov else packet


TOL = {
    torch.float16: (1e-2, 1e-2),
    torch.bfloat16: (5e-2, 5e-2),
    torch.float32: (1e-4, 1e-5),
}


@pytest.mark.parametrize(
    "overload,recipe,module,cls_name,dtypes,extra",
    ROUTES,
    ids=[r[0] for r in ROUTES],
)
def test_matches_aten(overload, recipe, module, cls_name, dtypes, extra):
    """Generated route agrees with the aten reference.

    Runs on a small shape by default. Every distinct shape costs a full
    TileLang compile (~4 s, since the availability gate forces
    TILELANG_DISABLE_CACHE=1 to dodge the upstream cache-key collision), so
    the larger manifest workload shape is opt-in via FLAGOS_TILEOPS_FULL=1.
    """
    shape = (64, 32)
    if os.environ.get("FLAGOS_TILEOPS_FULL") == "1":
        shape = WORKLOADS.get(overload, shape)
    dtype = getattr(torch, dtypes[0])

    fn = tileops_backend.build_impl(recipe, module, cls_name, dtypes, extra, overload)
    if fn is None:
        pytest.skip("route not constructible on this host")

    cpu_args = tileops_backend.sample_inputs(
        recipe, shape, dtype, device="cpu", overload=overload
    )
    dev_args = tuple(
        a.to("flagos") if isinstance(a, torch.Tensor) else a for a in cpu_args
    )

    got = fn(*dev_args)
    want = _ref(overload)(*cpu_args)
    if isinstance(got, (tuple, list)):
        got = got[0]
    if isinstance(want, (tuple, list)):
        want = want[0]
    if dtype in TOL:
        rtol, atol = TOL[dtype]
        torch.testing.assert_close(
            got.cpu().float(), want.float(), rtol=rtol, atol=atol
        )
    else:
        # Integer and bool results must be bit-exact.
        assert torch.equal(got.cpu(), want)


def test_dtype_guard_falls_back():
    """An unsupported dtype must fall back to aten, not raise."""
    x = torch.ones(64, device="flagos", dtype=torch.int32)
    assert torch.equal(torch.relu(x), x)


@pytest.mark.parametrize("overload", [r[0] for r in ROUTES])
def test_route_is_registered(overload):
    """Every generated route is known to the runtime."""
    assert overload in tileops_backend.registered_ops()


@pytest.mark.parametrize("overload,shim", sorted(SHIM_NAMES.items()))
def test_shim_exists_and_is_callable(overload, shim):
    """Each route has the callable its C++ stub resolves by name.

    CallPythonOp_Generic looks the function up by string on first call, so a
    rename that misses one side fails at runtime, on that one op, only once
    it is exercised. Checking the whole table here surfaces it immediately.
    """
    from torch_fl.generated import tileops_shims

    assert callable(getattr(tileops_shims, shim)), f"{overload} -> {shim}"


def test_dispatches_through_cpp():
    """The route is reached via the C++ dispatcher, not just callable.

    Every other test here calls build_impl or the shim directly, which
    would keep passing if the generated .cc stubs were never compiled in
    or the conf never routed to them. This one runs a subprocess with
    FLAGOS_USE_TILEOPS=1 and reads the dispatcher's own log line, so it
    fails if the C++ registration is missing. The FLAGOS_OP_ half proves
    the per-op override reaches TileOPs routes -- the feature that had to
    be reimplemented in Python back when registration lived there.
    """
    prog = (
        "import torch, torch_fl; "
        "torch.relu(torch.randn(64, 32, device='flagos', dtype=torch.float16))"
    )
    # Propagate this interpreter's import path: torch_fl and tileops are
    # commonly run from a source checkout / PYTHONPATH rather than being
    # installed, and a bare subprocess would just fail to import them --
    # which would read as a dispatch failure.
    base = dict(
        os.environ,
        FLAGOS_USE_TILEOPS="1",
        FLAGOS_LOG_DISPATCH="1",
        PYTHONPATH=os.pathsep.join(p for p in sys.path if p),
    )
    # importing torch_fl (which this module does at collection time) writes
    # the resolved conf path back into os.environ. Inherited by the child it
    # outranks FLAGOS_USE_TILEOPS, pinning it to whichever conf the *parent*
    # happened to select.
    base.pop("FLAGOS_BACKEND_CONFIG", None)

    out = subprocess.run(
        [sys.executable, "-c", prog], env=base, capture_output=True, text=True
    )
    assert "[flagos dispatch] relu -> tileops" in out.stdout + out.stderr, (
        f"stdout={out.stdout}\nstderr={out.stderr}"
    )

    out = subprocess.run(
        [sys.executable, "-c", prog],
        env=dict(base, FLAGOS_OP_relu="cuda"),
        capture_output=True,
        text=True,
    )
    assert "[flagos dispatch] relu -> cuda" in out.stdout + out.stderr, (
        f"stdout={out.stdout}\nstderr={out.stderr}"
    )
