# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# AUTO-GENERATED by scripts/codegen_tileops.py -- DO NOT EDIT.
"""Numeric and dispatch coverage for generated TileOPs routes."""

import os

import pytest
import torch

import torch_fl  # noqa: F401
from torch_fl import tileops_backend
from torch_fl.generated.tileops_routes import ROUTES, WORKLOADS

pytestmark = pytest.mark.skipif(
    not tileops_backend.is_tileops_available(),
    reason="TileOPs unavailable or host is not SM90",
)


def _ref(overload):
    """Resolve an aten overload to a callable.

    Called with CPU tensors on purpose: the flagos key is where the TileOPs
    impl is bound, so a reference computed there would just re-enter the
    implementation under test.
    """
    base, _, ov = overload.partition(".")
    packet = getattr(torch.ops.aten, base)
    return getattr(packet, ov) if ov else packet


TOL = {
    torch.float16: (1e-2, 1e-2),
    torch.bfloat16: (5e-2, 5e-2),
    torch.float32: (1e-4, 1e-5),
}


@pytest.mark.parametrize(
    "overload,recipe,module,cls_name,dtypes,extra",
    ROUTES,
    ids=[r[0] for r in ROUTES],
)
def test_matches_aten(overload, recipe, module, cls_name, dtypes, extra):
    """Generated route agrees with the aten reference.

    Runs on a small shape by default. Every distinct shape costs a full
    TileLang compile (~4 s, since the availability gate forces
    TILELANG_DISABLE_CACHE=1 to dodge the upstream cache-key collision), so
    the larger manifest workload shape is opt-in via FLAGOS_TILEOPS_FULL=1.
    """
    shape = (64, 32)
    if os.environ.get("FLAGOS_TILEOPS_FULL") == "1":
        shape = WORKLOADS.get(overload, shape)
    dtype = getattr(torch, dtypes[0])

    fn = tileops_backend.build_impl(recipe, module, cls_name, dtypes, extra, overload)
    if fn is None:
        pytest.skip("route not constructible on this host")

    cpu_args = tileops_backend.sample_inputs(
        recipe, shape, dtype, device="cpu", overload=overload
    )
    dev_args = tuple(
        a.to("flagos") if isinstance(a, torch.Tensor) else a for a in cpu_args
    )

    got = fn(*dev_args)
    want = _ref(overload)(*cpu_args)
    if isinstance(got, (tuple, list)):
        got = got[0]
    if isinstance(want, (tuple, list)):
        want = want[0]
    if dtype in TOL:
        rtol, atol = TOL[dtype]
        torch.testing.assert_close(
            got.cpu().float(), want.float(), rtol=rtol, atol=atol
        )
    else:
        # Integer and bool results must be bit-exact.
        assert torch.equal(got.cpu(), want)


def test_dtype_guard_falls_back():
    """An unsupported dtype must fall back to aten, not raise."""
    x = torch.ones(64, device="flagos", dtype=torch.int32)
    assert torch.equal(torch.relu(x), x)


def test_enable_is_idempotent():
    """Re-enabling must not double-register or grow the instance cache."""
    first = tileops_backend.enable_tileops_for_flagos()
    second = tileops_backend.enable_tileops_for_flagos()
    assert first == second


@pytest.mark.parametrize("overload", [r[0] for r in ROUTES])
def test_registered_on_privateuse1(overload):
    """Every generated route is actually bound for the flagos key."""
    tileops_backend.enable_tileops_for_flagos()
    assert overload in tileops_backend.registered_ops()


def test_env_override_is_consulted(monkeypatch):
    """FLAGOS_OP_<op>=cuda must keep the op off the tileops path.

    A PrivateUse1 binding intercepts before the C++ dispatcher, so honoring
    the override there alone is not enough -- the op has to stay unbound.
    Only the decision is asserted here: a PrivateUse1 binding made by an
    earlier test cannot be undone, so re-running enable() proves nothing.
    """
    monkeypatch.setenv("FLAGOS_OP_relu", "cuda")
    monkeypatch.setenv("FLAGOS_OP_sum__dim_IntList", "cuda")
    assert tileops_backend._env_override_backend("relu") == "cuda"
    assert tileops_backend._env_override_backend("sum.dim_IntList") == "cuda"
    assert tileops_backend._env_override_backend("sigmoid") is None
