# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import runpy
from pathlib import Path

import setuptools
from setuptools import Distribution
from setuptools.command.build_ext import build_ext


ROOT = Path(__file__).resolve().parents[2]


def _load_setup(monkeypatch):
    kwargs = {}
    monkeypatch.setattr(setuptools, "setup", lambda **values: kwargs.update(values))
    namespace = runpy.run_path(str(ROOT / "setup.py"))
    return namespace, kwargs


def test_build_ext_stages_generated_build_config(monkeypatch, tmp_path):
    _, setup_kwargs = _load_setup(monkeypatch)
    source_root = tmp_path / "source"
    package_root = source_root / "torch_fl"
    package_root.mkdir(parents=True)

    command_type = setup_kwargs["cmdclass"]["build_ext"]
    setup_globals = command_type.run.__globals__
    monkeypatch.setitem(setup_globals, "BASE_DIR", str(source_root))
    monkeypatch.setitem(setup_globals, "ACCELERATOR", "musa")
    monkeypatch.setitem(
        setup_globals,
        "build_deps",
        lambda: setup_globals["_write_build_config"](),
    )
    monkeypatch.setattr(build_ext, "run", lambda self: None)

    command = command_type(Distribution(setup_kwargs))
    command.ensure_finalized()
    command.build_lib = str(tmp_path / "wheel")
    command.run()

    staged = tmp_path / "wheel" / "torch_fl" / "_build_config.py"
    assert staged.read_text(encoding="utf-8") == (
        "# AUTO-GENERATED by setup.py at build time. Do not edit.\n"
        'ACCELERATOR = "musa"\n'
    )
