# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
import runpy
from pathlib import Path

import pytest
import setuptools
from setuptools import Distribution
from setuptools.command.build_ext import build_ext


ROOT = Path(__file__).resolve().parents[2]

KERNEL_SWITCHES = (
    "FLAGOS_BUILD_VENDOR",
    "FLAGOS_BUILD_FLAGGEMS",
    "FLAGOS_BUILD_BOXING",
    "FLAGOS_BUILD_FLAGGEMS_CPP",
    "FLAGOS_BUILD_TILEOPS",
)


def _load_setup(monkeypatch):
    kwargs = {}
    monkeypatch.setattr(setuptools, "setup", lambda **values: kwargs.update(values))
    namespace = runpy.run_path(str(ROOT / "setup.py"))
    return namespace, kwargs


@pytest.fixture
def clean_kernel_env(monkeypatch):
    """No build switch inherited from the ambient environment."""
    monkeypatch.delenv("FLAGOS_ACCELERATOR", raising=False)
    for name in KERNEL_SWITCHES:
        monkeypatch.delenv(name, raising=False)


def test_build_ext_stages_generated_build_config(
    monkeypatch, tmp_path, clean_kernel_env
):
    _, setup_kwargs = _load_setup(monkeypatch)
    source_root = tmp_path / "source"
    package_root = source_root / "torch_fl"
    package_root.mkdir(parents=True)

    command_type = setup_kwargs["cmdclass"]["build_ext"]
    setup_globals = command_type.run.__globals__
    monkeypatch.setitem(setup_globals, "BASE_DIR", str(source_root))
    monkeypatch.setitem(setup_globals, "FLAGOS_ACCELERATOR", "musa")
    monkeypatch.setitem(
        setup_globals,
        "build_deps",
        lambda: setup_globals["_write_build_config"](),
    )
    monkeypatch.setattr(build_ext, "run", lambda self: None)

    command = command_type(Distribution(setup_kwargs))
    command.ensure_finalized()
    command.build_lib = str(tmp_path / "wheel")
    command.run()

    staged = tmp_path / "wheel" / "torch_fl" / "_build_config.py"
    assert staged.read_text(encoding="utf-8") == (
        "# AUTO-GENERATED by setup.py at build time. Do not edit.\n"
        'ACCELERATOR = "musa"\n'
        'KERNELS = ("flaggems", "vendor")\n'
    )


def test_build_config_is_executable_python(monkeypatch, tmp_path, clean_kernel_env):
    """The generated file is imported by torch_fl._env.build_kernels()."""
    namespace, _ = _load_setup(monkeypatch)
    root = tmp_path / "src"
    (root / "torch_fl").mkdir(parents=True)
    # run_path returns a copy, so the redirect has to go through the function's
    # own globals -- assigning into `namespace` would leave BASE_DIR alone.
    globals_ = namespace["_write_build_config"].__globals__
    monkeypatch.setitem(globals_, "BASE_DIR", str(root))
    monkeypatch.setitem(globals_, "FLAGOS_ACCELERATOR", "cuda")
    namespace["_write_build_config"]()

    generated = {}
    exec((root / "torch_fl" / "_build_config.py").read_text("utf-8"), generated)
    assert generated["ACCELERATOR"] == "cuda"
    # CUDA builds every set, including the SM90-only TileOps.
    assert generated["KERNELS"] == (
        "boxing",
        "flaggems",
        "flaggems_cpp",
        "tileops",
        "vendor",
    )


@pytest.mark.parametrize(
    "accelerator, expected",
    [
        # CUDA compiles everything; every other platform drops at least TileOps,
        # and the non-CUDA-compatible vendors drop the CUDA boxing wrappers too.
        ("cuda", {"vendor", "flaggems", "boxing", "flaggems_cpp", "tileops"}),
        ("metax", {"flaggems", "boxing"}),
        ("ascend", {"vendor", "flaggems"}),
        ("dcu", {"vendor", "flaggems", "boxing"}),
        ("ppu", {"vendor", "flaggems", "boxing"}),
        ("tsingmicro", {"vendor", "flaggems", "boxing", "flaggems_cpp"}),
        ("gcu", {"vendor", "flaggems"}),
        ("musa", {"vendor", "flaggems"}),
        # BPU keeps the FLAGOS_BUILD_VENDOR default, but csrc/aten/backends/bpu/ does
        # not exist, so "vendor" here records a switch that is on rather than a
        # kernel set that is present.
        ("bpu", {"vendor", "boxing"}),
    ],
)
def test_default_kernel_set_per_accelerator(
    monkeypatch, accelerator, expected, clean_kernel_env
):
    namespace, _ = _load_setup(monkeypatch)
    resolved = namespace["_kernel_switches"](accelerator)
    names = namespace["KERNEL_SET_NAME"]
    assert {names[switch] for switch, on in resolved.items() if on} == expected


def test_explicit_kernel_switch_overrides_the_vendor_default(
    monkeypatch, clean_kernel_env
):
    """MetaX builds FlagGems into the boxing wheel by default, but not always."""
    namespace, _ = _load_setup(monkeypatch)
    monkeypatch.setenv("FLAGOS_BUILD_FLAGGEMS", "0")
    assert namespace["_kernel_switches"]("metax")["FLAGOS_BUILD_FLAGGEMS"] is False
    # And on CUDA the same variable turns it off too.
    assert namespace["_kernel_switches"]("cuda")["FLAGOS_BUILD_FLAGGEMS"] is False


def test_kernel_switch_uses_the_shared_truth_table(monkeypatch, clean_kernel_env):
    """The build-side parser must not accept what the runtime side rejects."""
    namespace, _ = _load_setup(monkeypatch)
    for raw, expected in (
        ("1", True),
        ("on", True),
        ("YES", True),
        ("  true  ", True),
        ("0", False),
        ("off", False),
        ("No", False),
        ("2", True),  # not a boolean: falls back to the vendor default, not "on"
    ):
        monkeypatch.setenv("FLAGOS_BUILD_VENDOR", raw)
        assert (
            namespace["_kernel_switches"]("cuda")["FLAGOS_BUILD_VENDOR"] is expected
        ), raw
    # On a set whose default is off the same input stays off, which is what
    # distinguishes "falls back to the default" from the hand-rolled parser's
    # "anything that is not 0/false/off/no is on".
    monkeypatch.setenv("FLAGOS_BUILD_TILEOPS", "2")
    assert namespace["_kernel_switches"]("metax")["FLAGOS_BUILD_TILEOPS"] is False


def test_cmake_kernel_set_names_match_the_build_record(monkeypatch):
    """csrc/CMakeLists.txt builds FLAGOS_BUILTIN_KERNELS from the same five set names.

    The names are spelled in CMake and in KERNEL_SET_NAME; the definition is what
    lets a dispatch failure say "this kernel set was not compiled into this
    wheel", so a rename on one side only would produce a wrong explanation.
    """
    namespace, _ = _load_setup(monkeypatch)
    cmake = (ROOT / "csrc" / "CMakeLists.txt").read_text(encoding="utf-8")
    block = cmake.split("set(FLAGOS_BUILTIN_KERNELS", 1)[1].split("message(STATUS", 1)[
        0
    ]
    pairs = re.findall(
        r"if\((\w+)\)\s*\n\s*string\(APPEND FLAGOS_BUILTIN_KERNELS \"([^,\"]+),\"\)",
        block,
    )
    assert dict(pairs) == namespace["KERNEL_SET_NAME"]


def test_impossible_kernel_switch_raises_instead_of_being_ignored(
    monkeypatch, clean_kernel_env
):
    """A MUSA build always links the vendor (mudnn) kernels, so asking for off is an error.

    Silently emitting the -D would be worse than failing: CMakeLists.txt forces
    the value anyway, and the build record would then claim a kernel set the
    wheel does not have.
    """
    namespace, _ = _load_setup(monkeypatch)
    monkeypatch.setenv("FLAGOS_BUILD_VENDOR", "0")
    with pytest.raises(ValueError, match="FLAGOS_BUILD_VENDOR"):
        namespace["_kernel_switches"]("musa")
    # The pin agrees with the default, so this is accepted.
    monkeypatch.setenv("FLAGOS_BUILD_VENDOR", "1")
    assert namespace["_kernel_switches"]("musa")["FLAGOS_BUILD_VENDOR"] is True
    # And a platform with no pin has no such objection.
    monkeypatch.setenv("FLAGOS_BUILD_FLAGGEMS_CPP", "1")
    assert namespace["_kernel_switches"]("ppu")["FLAGOS_BUILD_FLAGGEMS_CPP"] is True
