#!/usr/bin/env python3
"""Generate the GCU FlagGems registration list.

``csrc/aten/backends/gcu/generated/gcu_flaggems_register.inc`` claims the
FlagGems Python ops on PrivateUse1 so that ``backends_gcu.conf`` can route them
to the ``flaggems`` backend. ``gcu_register.inc`` only covers the ops topsaten
has a kernel for, so without this file most FlagGems routes have no registered
slot: the call does not box to CPU, it reaches the dispatcher's empty
``kFlagGems`` slot and raises "backend not registered".

The list is ``FLAGGEMS_PYTHON_OPS`` minus ``NATIVE_TRITON_GAPS['gcu']``, minus
``FLAGGEMS_PENDING_NATIVE_OPS`` (for as long as ``gcu`` is in
``FLAGGEMS_PENDING_NATIVE_VENDORS``), minus whatever ``gcu_register.inc``
already claims. Each op is emitted with the
wrapper symbol read back from the CUDA codegen's ``generated/register.inc``
rather than derived from the op name: ``add.Tensor`` is served by
``WrapperAddTensor`` while ``_adaptive_avg_pool2d`` is served by
``WrapperPrivAdaptiveAvgPool2d``, and only the generated file knows which is
which -- guessing the prefix is what broke the first version of the MUSA file.

The pending subtraction is what keeps this generator in step with
``gen_vendor_confs.py``: that script's ``build_all()`` holds the same set off
``flaggems`` in the confs, so registering an op here that the conf does not
route would add an m.impl() nothing dispatches to while changing which op the
conf sends to topsaten. Both sides must read the same set, or re-running one
generator alone silently moves the other's routes.

Usage:
    python3 scripts/codegen/codegen_gcu_flaggems.py            # rewrite the .inc
    python3 scripts/codegen/codegen_gcu_flaggems.py --check    # exit 1 if stale
"""

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import gen_vendor_confs as g  # noqa: E402
from backend_coverage import FLAGGEMS_PYTHON_OPS  # noqa: E402
from codegen_mudnn import REGISTER_INC, wrapper_map  # noqa: E402

REPO = Path(__file__).resolve().parent.parent.parent
OUT_INC = REPO / "csrc/aten/backends/gcu/generated/gcu_flaggems_register.inc"

INC_HEADER = """\
// Copyright (c) 2026, BAAI. All rights reserved.
//
// @generated by scripts/codegen/codegen_gcu_flaggems.py -- DO NOT EDIT.
//
// m.impl() lines for the FlagGems Python ops GCU routes to the `flaggems`
// backend. Included by register.cc inside TORCH_LIBRARY_IMPL(aten, PrivateUse1)
// when USE_GCU and FLAGOS_FLAGGEMS_PYTHON are set, directly after
// gcu_register.inc. The two lists together are the set of ops GCU claims on
// PrivateUse1: gcu_register.inc takes the ops topsaten has a kernel for, this
// one takes the rest of the FlagGems coverage. An op routed to `flaggems` that
// neither list claims reaches the dispatcher with an empty kFlagGems slot and
// raises "backend not registered" instead of falling back to cpu_fallback.
//
// Ops already claimed by gcu_register.inc are omitted here: a second m.impl()
// for the same op and dispatch key only overrides the first and warns at import.
//
// Excluded below NATIVE_TRITON_GAPS['gcu'] (scripts/codegen/gen_vendor_confs.py), each
// one measured failing on the S60 rather than assumed; see the comment on that
// set for the diagnosis behind every entry.
"""


def target_ops() -> list:
    """Sorted op list to register, with the exclusion reasons attached."""
    wrappers = wrapper_map()
    if not wrappers:
        raise SystemExit(
            f"{REGISTER_INC.relative_to(REPO)} is missing or empty; run "
            "scripts/codegen/codegen_ops.py first -- the wrapper symbols are read from it."
        )

    native = g.registered_impls(
        REPO / "csrc/aten/backends/gcu/generated/gcu_register.inc"
    )
    gaps = g.NATIVE_TRITON_GAPS.get("gcu", set())
    pending = (
        g.FLAGGEMS_PENDING_NATIVE_OPS
        if "gcu" in g.FLAGGEMS_PENDING_NATIVE_VENDORS
        else frozenset()
    )

    wanted = (set(FLAGGEMS_PYTHON_OPS) - gaps) - native - pending
    unknown = sorted(wanted - set(wrappers))
    if unknown:
        raise SystemExit(
            "no generated wrapper for: "
            + ", ".join(unknown)
            + f"\n{REGISTER_INC.relative_to(REPO)} has no m.impl() line for these ops."
        )

    return (
        sorted(wanted),
        sorted((native & set(FLAGGEMS_PYTHON_OPS)) - pending),
        sorted(gaps),
    )


def render() -> str:
    ops, via_native, gaps = target_ops()
    lines = [INC_HEADER]
    lines.append("// Excluded ops, routed back to topsaten or left to cpu_fallback:\n")
    for op in gaps:
        lines.append(f"//   - {op}\n")
    lines.append("//\n")
    lines.append(
        f"// Total: {len(ops)} ops registered here, {len(via_native)} further "
        f"FlagGems ops already claimed by gcu_register.inc.\n\n"
    )
    wrappers = wrapper_map()
    lines.extend(f'  m.impl("{op}", {wrappers[op]});\n' for op in ops)
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed .inc is stale instead of rewriting it",
    )
    args = ap.parse_args()

    text = render()
    rel = OUT_INC.relative_to(REPO)

    if args.check:
        current = OUT_INC.read_text() if OUT_INC.exists() else ""
        if current != text:
            script = Path(__file__).resolve().relative_to(REPO)
            raise SystemExit(f"{rel} is stale; run: python3 {script}")
        print(f"[check] {rel} is up to date")
        return

    OUT_INC.parent.mkdir(parents=True, exist_ok=True)
    OUT_INC.write_text(text)
    ops, via_native, gaps = target_ops()
    print(f"[gen] {rel}  ({len(ops)} m.impl lines, {len(gaps)} gaps excluded)")
    print(
        f"      {len(via_native)} FlagGems ops already registered by gcu_register.inc"
    )


if __name__ == "__main__":
    main()
