#!/usr/bin/env python3
"""Generate the CUPTI runtime API cbid -> name table.

``csrc/profiler/cupti_device_tracer.cc`` names every ``CUPTI_ACTIVITY_KIND_RUNTIME``
record through ``cuptiRuntimeCbidToName`` in ``csrc/profiler/cupti_shim.h``. That
table used to be hand-written and held ~20 ids, so every other callback id fell
through to the generic label ``cudaRuntime``: on CUDA a plain matmul workload
reported 180 of 203 runtime events that way, and on PPU 72 of 117. The raw
numeric cbid was always present in the event metadata, so the information was in
the trace the whole time; only the lookup was missing.

A hand-maintained table is also the wrong shape for this data. The ids are
assigned by the vendor header and are stable and append-only, the header is
generated by CUDA itself, and a wrong entry is invisible at runtime -- a
plausible label is emitted rather than an error. So the table is derived from the
header instead of maintained.

Two committed artifacts, because the vendor header is not in the repository and
the build must not depend on it:

``csrc/profiler/generated/cupti_runtime_cbid.txt``
    The parse result: one ``<cbid> <api name>`` line per id, in id order, under a
    provenance header recording the CUPTI and CUDA versions it came from and the
    sha256 of that header. Human-readable, so a refresh diff says which ids moved
    rather than which array offsets did.

``csrc/profiler/generated/cupti_runtime_cbid_names.inc``
    The C++ the shim includes, emitted from the ``.txt`` above.

Splitting them is what makes the table checkable in CI: ``--check`` re-renders
the ``.inc`` from the committed ``.txt`` and needs no vendor header, so a
hand-edit to either file fails the Codegen checks job. Only ``--refresh``, which
re-parses the vendor header, needs one -- and that is a deliberate, reviewed
action, not something a build does.

Usage:
    python3 scripts/codegen/gen_cupti_runtime_cbid.py --check
    python3 scripts/codegen/gen_cupti_runtime_cbid.py
    python3 scripts/codegen/gen_cupti_runtime_cbid.py --refresh [--header PATH]
"""

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
SCRIPT = Path(__file__).resolve()
OUT_TXT = REPO / "csrc/profiler/generated/cupti_runtime_cbid.txt"
OUT_INC = REPO / "csrc/profiler/generated/cupti_runtime_cbid_names.inc"

# Where a CUPTI install keeps its generated cbid header, most specific first.
# CUDA_HOME/CUDA_PATH cover a toolkit that is not under /usr/local/cuda, which is
# how the PPU build finds it (CUDA_HOME=$PPU_SDK/CUDA_SDK).
HEADER_CANDIDATES = (
    "/usr/local/cuda/extras/CUPTI/include/cupti_runtime_cbid.h",
    "{cuda_home}/extras/CUPTI/include/cupti_runtime_cbid.h",
    "{cuda_home}/targets/x86_64-linux/include/cupti_runtime_cbid.h",
)

# `CUPTI_RUNTIME_TRACE_CBID_<token> = <decimal>,`. The two non-API members are
# excluded explicitly: `INVALID` is the zero sentinel and `SIZE` is the count, and
# `FORCE_INT` is hex so it never matches the decimal group.
ENTRY_RE = re.compile(
    r"^\s*CUPTI_RUNTIME_TRACE_CBID_(?P<token>\w+)\s*=\s*(?P<cbid>\d+)\s*,\s*$"
)
SKIP_TOKENS = {"INVALID", "SIZE", "FORCE_INT"}

# `<api>`, optionally with CUPTI's `_ptsz` marker (the per-thread-default-stream
# variant of the same entry point) and always with a `_vNNNNN` version suffix.
# Both describe the same runtime API, so `cudaMemcpyAsync_ptsz_v7000` and
# `cudaMemcpyAsync_v3020` must both render as `cudaMemcpyAsync` -- a trace label
# is read by a human, and two spellings of one call is the collapse this table
# exists to undo.
VERSION_SUFFIX_RE = re.compile(r"_v\d+$")
PTSZ_SUFFIX_RE = re.compile(r"_ptsz$")

INC_HEADER = """\
// Copyright 2026 FlagOS Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by scripts/codegen/gen_cupti_runtime_cbid.py -- DO NOT EDIT.
// Derived from {cuda_version} CUPTI's cupti_runtime_cbid.h ({api_version_str}),
// sha256 {sha256}.
//
// Runtime API callback id -> name, indexed by the id itself. Entries that CUPTI
// declares but do not name an API (the INVALID sentinel) are null, and the
// caller in cupti_shim.h maps null and out-of-range alike to its generic label.
//
// Included at file scope, not inside a namespace: the namespace is opened here.
//
// Regenerate with:
//     python3 scripts/codegen/gen_cupti_runtime_cbid.py --refresh
// and commit both this file and cupti_runtime_cbid.txt.
"""

PROVENANCE_INTRO = """\
# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @generated by scripts/codegen/gen_cupti_runtime_cbid.py -- DO NOT EDIT.
#
# CUPTI runtime API callback ids and their names, one `<cbid> <name>` per line
# in id order. Regenerate alongside cupti_runtime_cbid_names.inc:
#
#     python3 scripts/codegen/gen_cupti_runtime_cbid.py --refresh --header PATH
#
# Ids are assigned by this vendor header and are stable and append-only, so a
# refresh from a newer toolkit only adds lines. That is also why the generated
# C++ is emitted from this file rather than from the header directly: the header
# is not part of the repository, and `--check` has to work without it.
"""


def find_header(explicit: str | None) -> Path:
    """Locate the vendor cbid header, or explain where one was looked for."""
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise SystemExit(f"--header {explicit} is not a file")
        return path

    cuda_home = os.environ.get("CUDA_HOME") or os.environ.get("CUDA_PATH") or ""
    tried = []
    for candidate in HEADER_CANDIDATES:
        path = Path(candidate.format(cuda_home=cuda_home))
        if path.is_file():
            return path
        tried.append(str(path))
    raise SystemExit(
        "no cupti_runtime_cbid.h found; pass --header PATH. Looked in:\n  "
        + "\n  ".join(tried)
    )


def parse_header(path: Path) -> tuple[dict[int, str], dict[str, str]]:
    """Return {cbid: api name} and the provenance to record for it."""
    raw = path.read_bytes()
    entries: dict[int, str] = {}
    for line in raw.decode("utf-8").splitlines():
        match = ENTRY_RE.match(line)
        if not match:
            continue
        token = match.group("token")
        if token in SKIP_TOKENS:
            continue
        name = VERSION_SUFFIX_RE.sub("", token)
        name = PTSZ_SUFFIX_RE.sub("", name)
        if not name:
            raise SystemExit(f"empty API name after normalising {token!r}")
        cbid = int(match.group("cbid"))
        # Duplicate ids would silently drop one of the two names.
        if cbid in entries:
            raise SystemExit(
                f"{path} assigns cbid {cbid} twice: {entries[cbid]!r} and {name!r}"
            )
        entries[cbid] = name

    if not entries:
        raise SystemExit(f"{path} yielded no CUPTI_RUNTIME_TRACE_CBID_ entries")

    cuda_version = ""
    for root in list(path.parents)[:4]:
        version_header = root / "include" / "cuda.h"
        if not version_header.is_file():
            continue
        found = re.search(
            r"^#define CUDA_VERSION\s+(\d+)",
            version_header.read_text(),
            re.MULTILINE,
        )
        if found:
            major, minor = divmod(int(found.group(1)), 1000)
            cuda_version = f"CUDA {major}.{minor}"
            break

    api_version = ""
    version_header = path.parent / "cupti_version.h"
    if version_header.is_file():
        found = re.search(
            r"^#define CUPTI_API_VERSION\s+(\d+)",
            version_header.read_text(),
            re.MULTILINE,
        )
        if found:
            api_version = found.group(1)

    provenance = {
        "source": path.name,
        "sha256": hashlib.sha256(raw).hexdigest(),
        "cuda_version": cuda_version or "unknown",
        "api_version": api_version or "unknown",
        "api_version_str": f"CUPTI_API_VERSION {api_version}"
        if api_version
        else "CUPTI_API_VERSION unknown",
        "entry_count": str(len(entries)),
        "max_cbid": str(max(entries)),
    }
    return entries, provenance


def render_txt(entries: dict[int, str], provenance: dict[str, str]) -> str:
    lines = [PROVENANCE_INTRO]
    lines.append(f"# source          : {provenance['source']}\n")
    lines.append(f"# sha256          : {provenance['sha256']}\n")
    lines.append(f"# cuda version    : {provenance['cuda_version']}\n")
    lines.append(f"# cupti api       : {provenance['api_version_str']}\n")
    lines.append(
        f"# entries         : {provenance['entry_count']} named ids, "
        f"highest id {provenance['max_cbid']}\n"
    )
    lines.append("#\n")
    for cbid in sorted(entries):
        lines.append(f"{cbid} {entries[cbid]}\n")
    return "".join(lines)


def parse_txt(text: str) -> tuple[dict[int, str], dict[str, str]]:
    """Read back a committed .txt, including the provenance it carries."""
    entries: dict[int, str] = {}
    provenance: dict[str, str] = {}
    labels = {
        "source": "source",
        "sha256": "sha256",
        "cuda version": "cuda_version",
        "cupti api": "api_version_str",
        "entries": "entry_count",
    }
    for line in text.splitlines():
        if line.startswith("#"):
            found = re.match(r"#\s*(.+?)\s*:\s*(.+?)\s*$", line)
            if found and found.group(1) in labels:
                provenance[labels[found.group(1)]] = found.group(2)
            continue
        if not line.strip():
            continue
        found = re.match(r"^(\d+)\s+(\S+)$", line)
        if not found:
            raise SystemExit(f"unparseable line in the committed table: {line!r}")
        entries[int(found.group(1))] = found.group(2)
    if not entries:
        raise SystemExit("the committed table has no entries")
    provenance.setdefault("entry_count", str(len(entries)))
    provenance.setdefault("max_cbid", str(max(entries)))
    return entries, provenance


def render_inc(entries: dict[int, str], provenance: dict[str, str]) -> str:
    count = max(entries) + 1
    header = (
        INC_HEADER.replace("{cuda_version}", provenance.get("cuda_version", "unknown"))
        .replace(
            "{api_version_str}",
            provenance.get("api_version_str", "CUPTI_API_VERSION unknown"),
        )
        .replace("{sha256}", provenance.get("sha256", "unknown"))
    )

    lines = [header]
    lines.append("\nnamespace flagos_cupti_runtime_cbid {\n\n")
    lines.append(f"inline constexpr size_t kNameCount = {count};\n\n")
    lines.append("inline constexpr const char* const kNames[kNameCount] = {\n")
    for cbid in range(count):
        name = entries.get(cbid)
        rendered = f'"{name}"' if name is not None else "nullptr"
        suffix = "," if cbid < count - 1 else ""
        lines.append(f"    {rendered}{suffix}  // {cbid}\n")
    lines.append("};\n\n")
    lines.append("}  // namespace flagos_cupti_runtime_cbid\n")
    return "".join(lines)


def _display(path: Path) -> str:
    """Render a path for a diagnostic, relative to the repo when it is inside it.

    Never raises: a stale-artifact message that itself blows up with a ValueError
    would report nothing at all, which is the one thing --check exists to avoid.
    """
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


def refresh(header: Path) -> tuple[dict[int, str], dict[str, str]]:
    entries, provenance = parse_header(header)
    OUT_TXT.parent.mkdir(parents=True, exist_ok=True)
    OUT_TXT.write_text(render_txt(entries, provenance))
    print(
        f"[gen] {_display(OUT_TXT)}  "
        f"({provenance['entry_count']} ids from {provenance['source']}, "
        f"{provenance['cuda_version']}, sha256 {provenance['sha256'][:12]})"
    )
    return entries, provenance


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed .inc is stale instead of rewriting it",
    )
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="re-parse a vendor cupti_runtime_cbid.h into the committed .txt first",
    )
    parser.add_argument(
        "--header",
        help="path to cupti_runtime_cbid.h (--refresh only; auto-located if omitted)",
    )
    args = parser.parse_args()

    if args.header and not args.refresh:
        raise SystemExit("--header only applies with --refresh")

    if args.refresh:
        if args.check:
            raise SystemExit("--refresh and --check are mutually exclusive")
        entries, provenance = refresh(find_header(args.header))
    else:
        if not OUT_TXT.is_file():
            raise SystemExit(
                f"{_display(OUT_TXT)} is missing; create it with --refresh"
            )
        entries, provenance = parse_txt(OUT_TXT.read_text())

    text = render_inc(entries, provenance)
    rel = _display(OUT_INC)

    if args.check:
        current = OUT_INC.read_text() if OUT_INC.is_file() else ""
        if current != text:
            raise SystemExit(
                f"{rel} does not match {_display(OUT_TXT)}; "
                f"run: python3 {_display(SCRIPT)}"
            )
        print(f"[check] {rel} is up to date ({len(entries)} named ids)")
        return

    OUT_INC.parent.mkdir(parents=True, exist_ok=True)
    OUT_INC.write_text(text)
    counts = len({name for name in entries.values()})
    print(
        f"[gen] {rel}  ({len(entries)} named ids -> {counts} distinct API names, "
        f"table of {max(entries) + 1})"
    )


if __name__ == "__main__":
    sys.exit(main())
